default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: farmstream_development

test:
  <<: *default
  database: farmstream_test

production:
  <<: *default
  database: farmstream_production
  username: farmstream
  password: <%= ENV['FARMSTREAM_DATABASE_PASSWORD'] %>
